### ISSUE TITLE
Can you share generate_rois.py code?

### ISSUE THREAD

**Issue by HelenZhuE** [CancerDataScience/SCNN#12]
Hi,

Can you please share generate_rois.py code here?

**Comment by LITTLEKKKK** [comment]
The same question.

**Comment by Richarizardd** [comment]
Hi - I have made the ROIs publicly available in a follow-up paper of this work:

https://github.com/mahmoodlab/PathomicFusion

Hope this helps!

**Comment by cooperlab** [comment]
I posted the ROI table in the repo here: https://github.com/PathologyDataScience/SCNN/blob/master/Table.S2.xls
