### ISSUE TITLE
Unable to locate model_train.py

### ISSUE THREAD

**Issue by xxTheYellowDartxx** [CancerDataScience/SCNN#13]
Hello - I have downloaded the docker image but I cannot seem to find the executable.  According to the read me file, it looks as though it should be in /root/scnn but it doesn't seem to be there.  I have searched the whole image with no luck.  Is it possible to download the executable another way?

**Comment by pooyam** [comment]
Hi,
We have not provided the executables in any repo other than this docker image so far.
I just checked this docker image, the executable python files "model_test.py" and "model_train.py" are both inside the "/root/scnn" folder. You should not have a problem seeing them if you are doing every step provided in the readme file.

**Comment by xxTheYellowDartxx** [comment]
Thank you for the response.  The issue that I was encountering was related to our system.  What was happening was a non-root user was unable to access /root within the image due to permissions but when accessing the image as root, the /root directory from the local compute node was mounting (we are using Singularity instead of Docker) so I was unable to see /root that was within the image.  By building the image locally as a sandbox, I was able to edit the permissions of /root within the image to allow non-root users to have R/X access to the scripts.
