### ISSUE TITLE
is nvidia-docker needed?

### ISSUE THREAD

**Issue by mingrui** [CancerDataScience/SCNN#5]
Hi!

Thanks for hosting this on docker.
I have tried it but the GPU training doesn't work.
Is nvidia-docker required?

Thank you!

**Comment by cooperlab** [comment]
Can you provide more details? "doesn't work" could be a lot of things.

This Docker contains all libraries needed to run GPU training and prediction using the configuration described in the paper. It is not guaranteed to work on any GPU as they vary widely in compute capabilities.
