### ISSUE TITLE
What's the encoding of the code?

### ISSUE THREAD

**Issue by Stand1987** [CancerDataScience/SCNN#6]
Hello,

Thanks for sharing your project!
But I just can't decode the code of 'model_train.py' and 'model_test.py'. 
Could you tell the encoding of the code?

**Comment by wellingtonyl** [comment]
me too, hope for the answer

**Comment by iridescent303** [comment]
Me too

**Comment by cooperlab** [comment]
We released a binary executable so that people can apply the code to the provided data or their own datasets. We did not release source code.
