### ISSUE TITLE
How to open those .py scripts?

### ISSUE THREAD

**Issue by HuangYu94** [CancerDataScience/SCNN#8]
Hello, I tried to pull your image and then I found the two python scripts: model_train.py and model_test.py. They seems to be unreadable after I tried vim to open them. I also tried sublime text and many other text editors... Could you please give me pointers on that or , if possible, release the python script on github? I am a PhD student working on similar topic and really want to learn from your implementation.

Thanks for your great help!

**Comment by cooperlab** [comment]
Hello. Please see the closed issues - the code is not provided. You should be able to use the Docker to run the analysis on the paper data and to adapt to your own dataset. Let us know if you have any questions.
