### ISSUE TITLE
"A full list of the whole-slide image files used in the paper" was not found

### ISSUE THREAD

**Issue by Shoriman** [CancerDataScience/SCNN#9]
@cooperlab 
### Background
I'd like to know a full list of the whole-slide image files used in the paper.
Therefore, I pulled the docker and start the container, as bellow;
```
$docker pull cancerdatascience/scnn:1.0
$docker run -it cancerdatascience/scnn:1.0 /bin/bash 
```

### Problem
In the README you say as follows;
> A full list of the whole-slide image files used in the paper is available in /data/rois.txt.

So I looked for `/data/rois.txt` as bellow, but not found;
```
root@5c46d8231b48:/# find / -name rois.txt
root@5c46d8231b48:/# find / -name data
```

Where can I find the full list?
Best,

**Comment by pooyam** [comment]
@Shoriman You can see the full list of used WSIs along with their corresponding information in paper's journal page 
http://www.pnas.org/content/115/13/E2970
Click on "Figures & SI" tab, then you'll see data under "Data supplements" section.

or you can directly download that data using the following link
http://www.pnas.org/highwire/filestream/800093/field_highwire_adjunct_files/0/pnas.1717139115.sd01.xls
